[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[dev]
  command = "npm --prefix frontend run dev"
  targetPort = 5173
  port = 8888
  envFiles = [".env"]
